import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') || 're_5D2Utgps_LrrWXd6cn7yhCH5LeE6esXu3';
const ADMIN_EMAIL = 'omike95@gmail.com';

function generatePassword(length = 12): string {
  const upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
  const lower = 'abcdefghjkmnpqrstuvwxyz';
  const digits = '23456789';
  const special = '!@#$%';
  const all = upper + lower + digits + special;
  const password = [
    upper[Math.floor(Math.random() * upper.length)],
    lower[Math.floor(Math.random() * lower.length)],
    digits[Math.floor(Math.random() * digits.length)],
    special[Math.floor(Math.random() * special.length)],
  ];
  for (let i = password.length; i < length; i++) {
    password.push(all[Math.floor(Math.random() * all.length)]);
  }
  for (let i = password.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [password[i], password[j]] = [password[j], password[i]];
  }
  return password.join('');
}

function row(label: string, value: string) {
  return `
    <tr>
      <td style="padding:10px 16px;background:#f9fafb;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:13px;width:40%;vertical-align:top;">${label}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #e5e7eb;color:#111827;font-size:13px;font-weight:500;">${value || '—'}</td>
    </tr>`;
}

function buildProfileEmail(profile: Record<string, string>) {
  const now = new Date().toLocaleString('en-GB', { dateStyle: 'full', timeStyle: 'short' });
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif;">
  <div style="max-width:620px;margin:32px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

    <!-- Header -->
    <div style="background:#1a4d2e;padding:28px 32px;text-align:center;">
      <h1 style="color:#ffffff;margin:0;font-size:20px;letter-spacing:0.5px;">NIDO Vietnam</h1>
      <p style="color:rgba(255,255,255,0.7);margin:6px 0 0;font-size:13px;">New Member Profile — Verification Required</p>
    </div>

    <!-- Alert Banner -->
    <div style="background:#fefce8;border-left:4px solid #f59e0b;padding:14px 24px;">
      <p style="margin:0;color:#92400e;font-size:13px;font-weight:600;">
        A new member account was created by an administrator on ${now}. Please review the profile below for verification.
      </p>
    </div>

    <!-- Profile Details -->
    <div style="padding:24px 32px;">
      <h2 style="margin:0 0 16px;color:#1a4d2e;font-size:16px;text-transform:uppercase;letter-spacing:0.5px;">
        ${profile.first_name} ${profile.last_name}
      </h2>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
        ${row('Email', profile.email)}
        ${row('Phone', profile.phone)}
        ${row('Date of Birth', profile.date_of_birth)}
        ${row('Gender', profile.gender)}
        ${row('Occupation', profile.occupation_type?.replace(/_/g, ' '))}
        ${row('Marital Status', profile.marital_status)}
        ${row('Vietnam City', profile.vietnam_city)}
        ${row('State of Origin', profile.nigerian_state_of_origin)}
      </table>
    </div>

    <!-- Footer -->
    <div style="background:#f9fafb;padding:20px 32px;border-top:1px solid #e5e7eb;text-align:center;">
      <p style="margin:0;color:#9ca3af;font-size:12px;">
        This email was automatically generated by NIDO Vietnam Admin System.<br>
        Login to the admin panel to activate, review passport data, or update this member's status.
      </p>
    </div>
  </div>
</body>
</html>`;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const {
      email, first_name, last_name, phone,
      date_of_birth, gender, occupation_type,
      marital_status, vietnam_city, nigerian_state_of_origin,
    } = await req.json();

    if (!email || !first_name || !last_name) {
      return new Response(JSON.stringify({ error: 'Email, first name and last name are required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    );

    const password = generatePassword();

    // Create the auth user
    const { data: userData, error: userError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { first_name, last_name },
    });

    if (userError) {
      return new Response(JSON.stringify({ error: userError.message }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const userId = userData.user?.id;

    // Upsert full profile
    if (userId) {
      const profileData: Record<string, unknown> = {
        id: userId, email, first_name, last_name,
        membership_status: 'pending',
      };
      if (phone) profileData.phone = phone;
      if (date_of_birth) profileData.date_of_birth = date_of_birth;
      if (gender) profileData.gender = gender;
      if (occupation_type) profileData.occupation_type = occupation_type;
      if (marital_status) profileData.marital_status = marital_status;
      if (vietnam_city) profileData.vietnam_city = vietnam_city;
      if (nigerian_state_of_origin) profileData.nigerian_state_of_origin = nigerian_state_of_origin;

      await supabaseAdmin.from('profiles').upsert(profileData, { onConflict: 'id' });
    }

    // Send profile notification email to admin for verification
    try {
      const emailHtml = buildProfileEmail({
        first_name, last_name, email,
        phone: phone || '', date_of_birth: date_of_birth || '',
        gender: gender || '', occupation_type: occupation_type || '',
        marital_status: marital_status || '', vietnam_city: vietnam_city || '',
        nigerian_state_of_origin: nigerian_state_of_origin || '',
      });

      const emailRes = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${RESEND_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: 'NIDO Vietnam <onboarding@resend.dev>',
          to: [ADMIN_EMAIL],
          subject: `New Member Profile — ${first_name} ${last_name} (Verification Required)`,
          html: emailHtml,
        }),
      });

      if (!emailRes.ok) {
        const errBody = await emailRes.text();
        console.error('Resend error:', errBody);
      }
    } catch (emailErr) {
      // Non-fatal — account is created regardless
      console.error('Email send failed:', emailErr);
    }

    return new Response(
      JSON.stringify({ success: true, user_id: userId, password }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (err) {
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
